### ISSUE TITLE
Entering new chamber members

### ISSUE THREAD

**Issue by vmlenz** [ETACoC/easttroy.org#5]
Hi Ben,
I entered two new businesses in ChamberMaster after we switched over to easttroy.org (I didn't realize it at the time). Can you transfer this info to the business listing on the new site or can I re-enter them?

They are: Pendragon Specialties and Modern Woodmen of America

**Comment by cgsmith** [comment]
This issue still exists.  The ticket should be reopened.

I think the problem is related to the request that is being sent over not being properly filtered.  The hashtag in the URI is what is breaking the site on this specific page. 

I would be more than willing to fix @bkeating - any chance at throwing the repo up with private access?
